#### System

[[plugins]] # Changes Vim working directory to project root
repo = 'airblade/vim-rooter'
hook_add = '''
  let g:rooter_patterns = ['.git/', 'Rakefile']
'''

[[plugins]] # Library for auto detect filetype
# Note: This plugin intend to call other plugins.
repo = 'Shougo/context_filetype.vim'

[[plugins]] # Auto detect and set filetype on cursor position
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']


#### Display, UI

[[plugins]] # Light-weight statusbar
repo = 'itchyny/lightline.vim'
hook_add = '''
  set laststatus=2
  set noshowmode
  if !has('win32') && !has('gui_running')
    set t_Co=256
  endif
  " display ALE status
  let g:lightline = {
        \ 'active': {
        \   'left': [
        \       ['mode', 'paste'],
        \       ['readonly', 'filename', 'modified'],
        \       ['linter_status'],
        \       ['linter_engines'],
        \       ['fixer_engines'],
        \       ['lsp_engine'],
        \     ],
        \   },
        \ 'component_function': {
        \     'linter_status': 'MyLinterStatus',
        \     'linter_engines': 'MyLinterEngines',
        \     'fixer_engines': 'MyFixerEngines',
        \     'lsp_engine': 'MyLspActiveServerName'
        \   }
        \}
'''


#### Tools

[[plugins]] # Asynchronous unite all interfaces
repo = 'Shougo/denite.nvim'
hook_add = '''
nnoremap [denite] <Nop>
"nmap <C-u> [denite]

nnoremap <silent> [denite]f :<C-u>Denite file_rec<CR>
nnoremap <silent> [denite]l :<C-u>Denite line<CR>
nnoremap <silent> [denite]u :<C-u>Denite file_mru<CR>
nnoremap <silent> [denite]y :<C-u>Denite neoyank<CR>

" Open result of Denite-grep with unique buffer name
nnoremap <silent> [denite]g :<C-u>Denite grep
      \ -buffer-name=search-buffer-denite<CR>
" Reopen result of Denite-grep
nnoremap <silent> [denite]r :<C-u>Denite
      \ -resume -buffer-name=search-buffer-denite<CR>
" Go to the next result of Denite-grep
nnoremap <silent> [denite]n :<C-u>Denite
      \ -resume -buffer-name=search-buffer-denite -select=+1 -imediately<CR>
" Back to the previous result of Denite-grep
nnoremap <silent> [denite]p :<C-u>Denite
      \ -resume -buffer-name=search-buffer-denite -select=-1 -imediately<CR>
'''

[[plugins]]
repo = 'previm/previm'
hook_add = '''
  if has('win32')
    let g:previm_open_cmd = 'start chrome'
  elseif has ('macunix')
    let g:previm_open_cmd = 'open -a "Google Chrome"'
  endif

  augroup PrevimSettings
    autocmd!
    autocmd BufNewFile,BufRead *.{md,mdwn,mkd,mkdn,mark*} set filetype=markdown
  augroup END
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

#### Syntax, Color scheme

#[[plugins]] # Colorscheme collections
#repo = 'flazz/vim-colorschemes'

[[plugins]] # for light colorscheme
repo = 'NLKNguyen/papercolor-theme'

[[plugins]] # for dark colorscheme
repo = 'jonathanfilip/vim-lucius'

[[plugins]] # Toml syntax highlight
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # Git wrapper so awesome.
repo = 'tpope/vim-fugitive'

#### Lint

[[plugins]] # ALE: Asynchronous Lint Engine
repo = 'w0rp/ale'
hook_add = '''
  " Keep the sign gutter open at all times
  let g:ale_sign_column_always = 1
  let g:ale_linter = {
        \   'javascript': ['eslint'],
        \   'json': ['jsonlint'],
        \   'python': ['flake8'],
        \   'sh': ['shellcheck'],
        \   'swift': ['swiftlint'],
        \   'vim': ['vint'],
        \}
  let g:ale_fixers = {
        \   'c': ['clang-format'],
        \   'cpp': ['clang-format'],
        \   'html': ['prettier'],
        \   'javascript': ['prettier'],
        \   'json': ['prettier'],
        \   'markdown': ['prettier'],
        \   'python': ['yapf'],
        \   'swift': ['swiftformat'],
        \}
  function! MyLinterStatus() abort
    " return string which indicate warning and errors detected by linter.
    let l:counts = ale#statusline#Count(bufnr(''))
    let l:all_errors = l:counts.error + l:counts.style_error
    let l:all_non_errors = l:counts.total - l:all_errors
    return l:counts.total == 0 ? '●' : printf(
                \   '▲%d ×%d',
                \   all_non_errors,
                \   all_errors
                \)
  endfunction
  function! MyLinterEngines() abort
    " return string which is list of enabled linters.
    let l:linters = has_key(g:ale_linter, &filetype) ?
          \ join(g:ale_linter[&filetype], ',') : '-'
    return printf('Lint<%s>', l:linters)
  endfunction
  function! MyFixerEngines() abort
    " return string which is list of enabled fixers.
    let l:fixers= has_key(g:ale_fixers, &filetype) ?
          \ join(g:ale_fixers[&filetype], ',') : '-'
    return printf('Fix<%s>', l:fixers)
  endfunction
  function! MyLspActiveServerName() abort
    " return string which is active lsp server name
    let s:status_lines = split(lsp#get_server_status(), '\n')
    let s:active_server_list_raw = map(s:status_lines, {idx, val ->
                \   matchstr(val, '^\zs[^:]*\ze:\srunning.*$', 0)
                \ })
    let s:active_server_list = filter(s:active_server_list_raw, {idx, val -> val !=# ''})
    let s:active_server_name = empty(s:active_server_list) ? '-': s:active_server_list[0]
    return 'Lsp<' . s:active_server_name . '>'
  endfunction
'''

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
depends = ['async.vim']
on_ft = ['typescript', 'python', 'go', 'ruby', 'c', 'cpp']
hook_add = '''
"disable diagnotics because using ALE
let g:lsp_diagnotics_enabled = 0
" https://gist.github.com/mattn/4583ef3e082691275b79674fedac357c
if executable('typescript-language-server')
  augroup LspTypeScript
    au!
    autocmd User lsp_setup call lsp#register_server({
        \ 'name': 'typescript-language-server',
        \ 'cmd': {server_info->[&shell, &shellcmdflag, 'typescript-language-server --stdio']},
        \ 'root_uri':{server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'tsconfig.json'))},
        \ 'whitelist': ['typescript'],
        \ })
    autocmd FileType typescript setlocal omnifunc=lsp#complete
  augroup END
endif
if executable('pyls')
  " pip install python-language-server
  augroup LspPython
    au!
    autocmd User lsp_setup call lsp#register_server({
        \ 'name': 'pyls',
        \ 'cmd': {server_info->['pyls']},
        \ 'whitelist': ['python'],
        \ })
    autocmd FileType python setlocal omnifunc=lsp#complete
  augroup END
endif
if executable('golsp')
  augroup LspGo
    au!
    autocmd User lsp_setup call lsp#register_server({
        \ 'name': 'go-lang',
        \ 'cmd': {server_info->['golsp']},
        \ 'whitelist': ['go'],
        \ })
    autocmd FileType go setlocal omnifunc=lsp#complete
    autocmd FileType python,go nmap gd <plug>(lsp-definition)
  augroup END
elseif executable('go-langserver')
  augroup LspGo
    au!
    autocmd User lsp_setup call lsp#register_server({
        \ 'name': 'go-lang',
        \ 'cmd': {server_info->['go-langserver', '-mode', 'stdio', '-gocodecompletion']},
        \ 'whitelist': ['go'],
        \ })
    autocmd FileType go setlocal omnifunc=lsp#complete
  augroup END
endif
if executable('solargraph')
  augroup LspRuby
    au!
    autocmd User lsp_setup call lsp#register_server({
        \ 'name': 'solargraph',
        \ 'cmd': {server_info->[&shell, &shellcmdflag, 'solargraph stdio']},
        \ 'whitelist': ['ruby'],
        \ })
    autocmd FileType ruby setlocal omnifunc=lsp#complete
  augroup END
endif
if executable('clangd')
  augroup LspCpp
    au!
    autocmd User lsp_setup call lsp#register_server({
        \ 'name': 'clangd',
        \ 'cmd': {server_info->['clangd']},
        \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp'],
        \ })
    autocmd FileType c,cpp setlocal omnifunc=lsp#complete
  augroup END
endif
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
